# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{utilio}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BJ Neilsen"]
  s.date = %q{2010-08-06}
  s.description = %q{}
  s.email = %q{bj.neilsen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".bundle/config",
     ".bundle/environment.rb",
     ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/utilio.rb",
     "lib/utilio/database.rb",
     "lib/utilio/path.rb",
     "spec/data/database.yml",
     "spec/data/path.yml",
     "spec/spec_helper.rb",
     "spec/utilio_database_spec.rb",
     "spec/utilio_path_spec.rb",
     "utilio.gemspec"
  ]
  s.homepage = %q{http://www.rand9.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A general collection of application utilities for dealing with paths and active_record}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/utilio_database_spec.rb",
     "spec/utilio_path_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

