# -*- encoding: utf-8 -*-
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require 'utilio/version'

Gem::Specification.new do |s|
  s.name        = 'utilio'
  s.version     = Utilio::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['BJ Neilsen', 'Bart Elison']
  s.email       = ['bj.neilsen@gmail.com', 'bart.elison@gmail.com']
  s.homepage    = 'http://www.rand9.com'
  s.summary     = 'A general collection of application utilities for dealing with paths and active_record, and security'
  s.description = 'A general collection of application utilities for dealing with paths and active_record and security'

  s.required_rubygems_version = '>= 1.3.6'
  s.rubyforge_project         = 'utilio'

  s.add_development_dependency 'bundler', '>= 1.0.0.rc.5'
	s.add_development_dependency 'guid'
	s.add_development_dependency 'rspec', '>= 2.0.0.beta.18'

  s.files        = `git ls-files`.split("\n")
  # s.executables  = `git ls-files`.split("\n").select{|f| f =~ /^bin/}
  s.require_path = 'lib'
end


# # Generated by jeweler
# # DO NOT EDIT THIS FILE DIRECTLY
# # Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# # -*- encoding: utf-8 -*-
# 
# Gem::Specification.new do |s|
#   s.name = %q{utilio}
#   s.version = "0.0.2"
# 
#   s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
#   s.authors = ["BJ Neilsen"]
#   s.date = %q{2010-08-17}
#   s.description = %q{}
#   s.email = %q{bj.neilsen@gmail.com}
#   s.extra_rdoc_files = [
#     "LICENSE",
#      "README.md"
#   ]
#   s.files = [
#     ".bundle/config",
#      ".bundle/environment.rb",
#      ".document",
#      ".gitignore",
#      "Gemfile",
#      "Gemfile.lock",
#      "LICENSE",
#      "README.md",
#      "Rakefile",
#      "VERSION",
#      "autotest/discover.rb",
#      "lib/utilio.rb",
#      "lib/utilio/database.rb",
#      "lib/utilio/path.rb",
#      "lib/utilio/security.rb",
#      "spec/spec_helper.rb",
#      "spec/utilio/config/database.yml",
#      "spec/utilio/data/path.yml",
#      "spec/utilio/database_spec.rb",
#      "spec/utilio/path_spec.rb",
#      "spec/utilio/security_spec.rb",
#      "utilio.gemspec"
#   ]
#   s.homepage = %q{http://www.rand9.com}
#   s.rdoc_options = ["--charset=UTF-8"]
#   s.require_paths = ["lib"]
#   s.rubygems_version = %q{1.3.7}
#   s.summary = %q{A general collection of application utilities for dealing with paths and active_record}
#   s.test_files = [
#     "spec/spec_helper.rb",
#      "spec/utilio/database_spec.rb",
#      "spec/utilio/path_spec.rb",
#      "spec/utilio/security_spec.rb"
#   ]
# 
#   if s.respond_to? :specification_version then
#     current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
#     s.specification_version = 3
# 
#     if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#       s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
#     else
#       s.add_dependency(%q<rspec>, [">= 1.2.9"])
#     end
#   else
#     s.add_dependency(%q<rspec>, [">= 1.2.9"])
#   end
# end
# 
